### ISSUE TITLE
[Task] Get Hearths to Register

### ISSUE THREAD

**Issue by Spydrouge** [opencog/unity3d-opencog-game#66]
### Observations
- It does appear that the robot can sense the Hearth. It prints "I can see my home! It is where I feel safe." It is not clear to me yet whether the robot will actively seek closer to its home if it feels 'unsafe.' However it's integrity does seem to go up when it's near the hearth. 
- The robot will gain integrity from a Hearth beside him. He will not, however, wander closer to a Hearth if his integrity is low. And since feeding him a battery gives him almost full integrity, I can't really test how he behaves when energy is high but integrity is low.
### Tasks
- [x] Run game and embodiment. See if OCSecureBlock has any impact on the game at all. 
- [x] Write follow-up tasks accordingly. 
- [x] Test to see if the robot will ever gravitate near the hearth (the map we play on is very small, so I should generate him at one end and the hearth at the other. 
- [x] Trace hearths through the backend to see if there is a rule for approaching them. 
- [ ] Find out where that rule gets lost
